server:
  port: 8082
spring:
  application:
    name: Peoples Application
  datasource:
    url: jdbc:mysql://localhost:3306/mac
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
