server:
  port: 8443
  ssl:
    enabled: true
    key-store: src/main/resources/kaleabkey.p12
    key-store-password: 12345678
    key-store-type: PKCS12
    key-alias: kaleabkey
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: tadewoskaleab@yahoo.com
    password: lionking@
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
  application:
    name: Peoples Application
  datasource:
    url: jdbc:mysql://localhost:3306/mac
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
scheduledEmailCron: '0 * * * * *'
emailAddress: kaleabero@gmail.com 
